### ISSUE TITLE
widget_gallery example crash on Windows [scroll, resize]

### ISSUE THREAD

**Issue by Eteokles** [linebender/druid#1144]
On Windows (works well on Linux)

`error: process didn't exit successfully: '...\druid-master\target\debug\examples\widget_gallery.exe' (exit code: 0xc000041d)`

To reproduce the issue, just scroll down to the end then try to resize the window. I reproduced the error on two different computer.

**Comment by raphlinus** [comment]
Confirm. Looking at the crash, it's in the `draw_bitmap` method. The bitmap argument is not a null pointer, but I wasn't able to validate it beyond that. The error code maps to STATUS_FATAL_USER_CALLBACK_EXCEPTION, which is also odd, because I don't see a user callback of any kind here.

This is somewhat mysterious. I haven't dug deeper, but wanted to post my results.

It's *possible* this is caused by creating the image resource in a DXGI DeviceContext, but switching to a hwnd render context during resize. If so, I can think of ways to fix this, but we should confirm.
