### ISSUE TITLE
LifeCycle::EnvChanged

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#1167]
This was mentioned by someone (@rjwittams?) during a previous discussion but I'd like to open a tracking issue; I think that we need an `EnvChanged` lifecycle event, so that widgets that use the env can invalidate themselves appropriately, and I would also like some mechanism for determining which env keys have changed, so that invalidation can be done only as necessary.

At some point we may want to investigate *diffing* the `Env`, but I think that is future work; what is important is that a widget is able to determine, when the `Env` changes, whether any of the changes involve keys that widget is interested in. The trivial version of this is just to pass the old and new `Env`s, and have the widget just directly check the keys it uses, like:

```rust
fn needs_to_rebuild_layout(old: &Env, new: &Env) -> bool {
    !old.get(KEY_I_USE).same(new.get(KEY_I_USE)) 
        || !old.get(OTHER_KEY_I_USE).same(new.get(OTHER_KEY_I_USE))
}
```

This is a relatively straight-forward project that involves some familiarity with druid internals, but should not pose serious problems; I would start with just adding a `LifeCycle::EnvChanged` event that is dispatched as part of `update` in `WidgetPod`. This should not recurse; it should be sent directly by each pod by comparing the new `Env` in update with the stored `Env`.

**Comment by raphlinus** [comment]
This seems reasonable to me. Are you thinking that environment changes would supplant `update`, so that the latter would only be called in the presence of data changes?

Re diffing (which I agree should be a future investigation), the im crate provides an "efficiently diffable map," and I think it might make sense to adopt something like that for Env storage. The code fragment above doesn't really show the value in such a thing, as a query to find out if a single key has changed should be cheap no matter what the data structure.

**Comment by cmyr** [comment]
The problem with update is that it only provides the new `Env`, so widgets can't tell what has changed. An alternative to this proposal would be to pass both old and new `Env` in `update`; I'm not necessarily opposed to this.

Another option (which I think has some problems, but might as well mention) is that the `Env` itself could get the functionality to be store a list of changed keys, and this would be available in `update`.

**Comment by raphlinus** [comment]
Right. But "changed" is not an absolute question, it's always "changed since when," and in the case of viewswitcher style dynamic behavior, that "when" cannot be assumed to be the last update cycle. So having a list of changed keys be stored in Env seems very problematic. That said, I don't want to totally shoot down the idea, it's possible it can be made to work and maybe could be very nice. Having a lighter way to see only what's changed is obviously a good thing.

Obviously widgets could stash a clone of the previous env, but this is wasteful, as the framework already needs to do that.

Supplying old Env on update seems possible. Another idea (in the spirit of brainstorming) is to make it available in the update context, to avoid having too much of a profusion of arguments.

**Comment by cmyr** [comment]
I agree that changes in env would be hard to get right. Throwing it in the `UpdateCtx` feels a bit hacky, but wouldn't break API and would also let us do something simple like,


```rust
if ctx.env_key_changed(env, MY_KEY) { .. }
```

which has a certain elegance..

**Comment by rjwittams** [comment]
Seems reasonable.

I guess you'd want a has_env_changed on the context as well - under this scheme update could be either:

* data change
* self or descendent requested
* env changed

Or any combination where at least one is true...

So you probably want it to be easy to tell how it was caused .. useful for data fiddling wrappers like lenswrap and scope etc I think to work out what updates to pass on to their children.

**Comment by cmyr** [comment]
My thinking was that instead of checking a `has_changed` flag and then checking for changed keys, it's probably easier in general to just always check the keys you care about, since I don't think a handful of hashmap lookups and a handful of `same` calls are going to have any noticeable performance impact, and it feels more straight-forward. It's also arguably harder to misuse; if you invalidate every time the env changes without checking that the changes affect you, you might potentially over-invalidate? This doesn't feel like a big problem in practice, though.

**Comment by rjwittams** [comment]
I don’t see how that works for e.g Lenswrap given the check it does now. It would not pass on updates to just the environment. 
So we are back to either
A) no wrapper should ever filter updates
B) it needs to be possible to know what caused an update so you can tell if your filtering is valid

**Comment by cmyr** [comment]
Good point, I see how transparent widgets would need some way of checking for any change at all. 👍
