### ISSUE TITLE
jitter while editing TextBox

### ISSUE THREAD

**Issue by cmyr** [linebender/druid#1406]
Not sure what's going on here, but it looks like something about the width of the text in the textbox is causing it to be positioned slightly differently? I see this on both linux and mac, so it's likely a druid thing.

![2020-11-17 10 51 45](https://user-images.githubusercontent.com/3330916/99412691-0276b580-28c3-11eb-86a5-27e3e1a931b6.gif)

**Comment by jneem** [comment]
#1091 maybe?

**Comment by cmyr** [comment]
I've seen this before that was merged so I don't think so.

**Comment by jneem** [comment]
Ok, not #1091, but the issue still seems to be rounding in the alignment. The problem is that the two widgets are packed into the same `Flex` and then aligned together, and so the alignment of the textbox within the flex is subject to rounding, as is the alignment of the flex within the window.

The fix is to align the label and textbox separately before packing them into the flex. It's a bit of a footgun, maybe, but I don't see what else we can do in general if we still want to round to pixels.
