### ISSUE TITLE
[feat] Expose a way to make images during `update`

### ISSUE THREAD

**Issue by derekdreery** [linebender/druid#1473]
When drawing text, a widget can (re)create the textlayout during update, by getting access to the `PietText`. It would be nice if there was an analagous way to create piet `Image`s during update. Currently, the image must always be rebuilt in `paint` or caching used in user code.

**Comment by raphlinus** [comment]
I totally agree with this, and have been doing some light thinking. It will require some changes in the Piet API. A very rough outline of my thinking is that Piet exposes a type that I'm calling "Session" for now, which is Clone and Send, and is suitable for creating all retained resources. That includes text layouts and images, and also retained display lists going forward.

There are some questions regarding the details, one of the biggest to me is whether we continue with the gfx-hal like tower of associated types, or have a more dynamic dispatch pattern, so that creating a resource from one type of Session and using it in another is a runtime error. There are some subtle issues here, as it's also possible to get Direct2D errors using resources created on one device in a [DeviceContext](https://docs.microsoft.com/en-us/windows/win32/api/d2d1_1/nn-d2d1_1-id2d1devicecontext#remarks) created from another.

**Comment by cmyr** [comment]
this should now be possible as of #1677, which brings in the [`RenderContext::capture_image_area`](https://docs.rs/piet/0.4.0/piet/trait.RenderContext.html#tymethod.capture_image_area) method.
