### ISSUE TITLE
Blessing a rope implementation, similar to `im` for immutable maps/lists/sets.

### ISSUE THREAD

**Issue by derekdreery** [linebender/druid#1535]
Would you consider blessing a rope crate (behind a feature flag like `im`), and implementing `Data` for it? Which rope crate?

**Comment by raphlinus** [comment]
We've had some discussions about this. I've done a bit of work on xi-rope, a bunch of which is in a local branch and not checked in, to make a proper vector like type, with the specific feature of making sparse diffs; this is not a feature that `im` has.

That's just lists. Maps and sets have somewhat different considerations - `im` *does* do sparse diffs for (ordered) maps, which is in some ways an easier problem because the ordering of the map keys synchronizes.
