### ISSUE TITLE
window_origin() of a widget on LifeCycle::WidgetAdded is always (0, 0) instead of it's actual position.

### ISSUE THREAD

**Issue by generatively** [linebender/druid#1719]
I assume this is due to this lifecycle event being sent prior to the widget being actually positioned by it's parent widget for some reason?

**Comment by cmyr** [comment]
Yes, `WidgetAdded` is always sent before anything else, including layout, and the widget does not have a window position until it is laid out.

Ideally you should be able to handle `LifeCycle::Size` and have this set correctly, but that's also not possible, because it is also sent before this state is configured.

It looks like there is a slightly hacky work around, though; you can handle `LifeCycle::Internal(InternalLifeCycle::ParentWindowOrigin)`; this is sent after each layout pass. If your widget manages any children, make sure that you forward this event to them afterwards.

**Comment by cmyr** [comment]
So I acknowledge that the current situation isn't great, but it's going to remain for at least the near future, I think this work around is viable.
