### ISSUE TITLE
Explanation of Target::Auto

### ISSUE THREAD

**Issue by arthmis** [linebender/druid#1731]
Is there meant to be an explanation of how the target is determined when using `Target::Auto` for command submissions? It seems it sends to the host window of the widget?

**Comment by cmyr** [comment]
It depends on where the command is submitted. If it is submitted from inside a `Widget` method, then it defaults to the host window for that widget; but if it is sent from outside the application (`ExtEventHandle`) or from the root `AppDelegate` then it defaults to being application-global.

**Comment by arthmis** [comment]
Ok cool, I just found that out when trying to send a command to another window from a different window. Should that be explained in the docs?

**Comment by cmyr** [comment]
I do think that the docs could be improved.

Basically users probably shouldn't need to use `Command::new` anymore. Instead you would do `MY_SELECTOR.with(some_payload).to(some_target)`, and the target is optional; we will use `Auto` if you don't provide a target. There should really never be a need for the user to specify `Auto` themselves.

**Comment by arthmis** [comment]
Ah I see, I've been creating the commands directly with `Command::new`.

**Comment by arthmis** [comment]
Even still, if I create the command that way then it still isn't obvious what Target::auto will send the command to. I can write something that says what you explained to me above for the `Auto` variant.

**Comment by cmyr** [comment]
Yea, I think that would be welcome. I think what's more important, though, is to push people away from `Command::new` in any example code; I might mention in the docs for `Target::Auto` that you shouldn't need to chose it explicitly (and I would also want to not use it in any examples; it is used currently.)

Feel free to take this on if you want, otherwise I'll keep this issue open for the next docs pass. :)
