### ISSUE TITLE
Support for Chrono behind feature flag

### ISSUE THREAD

**Issue by arthmis** [linebender/druid#1736]
It would nice to have `Data` implemented for Chrono data types behind a feature flag. It's not very essential I think though.

**Comment by cmyr** [comment]
This is a tricky question. In theory there are an unlimited number of external types, and it's hard to determine what should qualify for inclusion for the purposes of `Data`. One concern is that this increases the cost of testing, since we want to test all features.

`chrono` feels like a reasonable thing to include, since it's so commonly used, and time is an important concept in a GUI. Especially since we will likely eventually ship a date picker, I think this makes sense.

**Comment by arthmis** [comment]
Yes for my case, it alleviates needing to implement `Data` manually for types that contain chrono types. It's not a problem, but just a bit annoying.
