### ISSUE TITLE
[Question] Lens in the list example

### ISSUE THREAD

**Issue by TENX-S** [linebender/druid#1810]
Hi, 

I've been reading the [list](https://github.com/linebender/druid/blob/master/druid/examples/list.rs) example for a while. The code snippet that confuses me most is lines 85 to 124. 
I guess the type of the `(shared, item)`, which is `&mut (Vector<u32>, u32)`, maybe depend on the following:
```rust
lens::Identity.map(
    |d: &AppData| (d.notes.clone(), d.notes.clone()),
    |d: &mut AppData, x: (Vector<Note>, Vector<Note>)| {
        d.notes = x.0
    }
)
```
I don't know much about the concept of lens, it seems to come from functional programming?
And how should I write the lens if I want to change the type of `&mut (Vector<u32>, u32)` to `&mut(Vector<u32>, u32, another field type)`.

Thank you !

**Comment by xarvic** [comment]
This is possible because of ListIter. The type `(S, Vector<T>)` implements `ListIter<(S, T)>`. This means `List` implements Widget<(S, Vector<T>)> if the inner widget implements `Widget<(S, T)>`. Since this is the only special case, changing the inner type to implement `Widget<(S, T, U)>` does not work at the moment.
