### ISSUE TITLE
Opening sub window from menu item

### ISSUE THREAD

**Issue by meettitan** [linebender/druid#1812]
`MenuEventCtx` currently does not have a way of spawning a sub window. I see `MenuEventCtx` doesn't store widget info the same way `EventCtx` does, so I'm unsure of how to make `SubWindowDesc` happy (it wants some IDs and a root widget).

[My longer winded Zulip question on the matter](https://xi.zulipchat.com/#narrow/stream/255910-druid-help/topic/MenuEventCtx.3A.3Anew_sub_window.28.29)

**Comment by jneem** [comment]
Ok, that's a good point. One option could be that we host the sub-window at the root widget, but that opens up some cross-platform issues because on macOS you can have a menu but no open windows (and so no root widget).

Would it be possible for you to use a new top-level window instead of a new sub-window? That feels like a better fit for opening from the menu...

**Comment by cmyr** [comment]
yes, subwindows are probably not the right solution here; a subwindow is intended for something like a modal or a drop-down menu.
