### ISSUE TITLE
Is druid a viable option for creating a GUI yet?

### ISSUE THREAD

**Issue by dumrich** [linebender/druid#1844]
Is druid close to feature-complete? Would it be theoretically possible to build a text editor in druid? If not, around when would this be possible?

**Comment by cmyr** [comment]
Druid is currently focused very specifically on the project of creating a font editor; it is not a near-term goal to make it a fully viable application framework for arbitrary applications, and I can't really give an honest estimate of when that might become possible; there is a huge amount of work required to get there.

A text editor in particular is a tricky problem, because text is a tricky problem. I think that you could use druid to write a reasonably good text editor today, but this would require you to really dig in to a lot of the text internals, and you would have to reimplement a lot of editing controls and related functionality.
