### ISSUE TITLE
Bad warning on the windows implementation of druid-shell for window builder

### ISSUE THREAD

**Issue by JAicewizard** [linebender/druid#1855]
This gives a warning for unimplemented windowlevels:
```
    pub fn set_level(&mut self, level: WindowLevel) {
        match level {
            WindowLevel::AppWindow | WindowLevel::Tooltip => self.level = Some(level),
            _ => {
                warn!("WindowBuilder::set_level({:?}) is currently unimplemented for Windows platforms.", level);
            }
        }
    }
```

But looking at the code to hangle `self.level`:
```
            if let Some(level) = self.level {
                match level {
                    WindowLevel::AppWindow => (),
                    WindowLevel::Tooltip => {
                        dwStyle = WS_POPUP;
                        dwExStyle = WS_EX_NOACTIVATE | WS_EX_TOOLWINDOW;
                        focusable = false;
                    }
                    WindowLevel::DropDown => {
                        dwStyle = WS_CHILD;
                        dwExStyle = 0;
                    }
                    WindowLevel::Modal => {
                        dwStyle = WS_OVERLAPPED;
                        dwExStyle = WS_EX_TOPMOST;
                    }
                }
            }
```

This all seems to be implemented.

**Comment by cmyr** [comment]
Is this related to #1824?

**Comment by JAicewizard** [comment]
related as in I found this while looking into that. This is in the `WindowBuilder` so not related to changing the window level after creating it.

**Comment by sjoshid** [comment]
I had the same question. It _looks_ like `WindowLevel::DropDown` is implemented but it's not actually there yet. If you handle the `WindowLevel::DropDown` (instead of showing warning) it'll throw error. That's because creating a child window requires parent's `HWND`  which shell doesnt have yet. 

Even after somehow supplying the `HWND` it still wont work because as soon as any widget in parent's window calls a paint refresh (like a cursor in textbox), the child window gets "hidden"

And even if you get that working, it still wont work because there seems be a scaling bug at least on Windows which places child windows at some weird places. 

I would be happy to provide more details if anyone is interested.

**Comment by JAicewizard** [comment]
Huh, might be worth adding that as a comment explaining, but anyways, thanks for explaining!

**Comment by sjoshid** [comment]
haha. I tried my best explaining. Sorry. 
I'll open a PR and let the code do the talking/explaining. 

Thanks.

**Comment by JAicewizard** [comment]
no your explaining was fine, just having a comment linking to it might be nice for future reference.
