### ISSUE TITLE
`with_text_alignment` does not appear to affect `Label` widget?

### ISSUE THREAD

**Issue by odakaui** [linebender/druid#1987]
Hi, 
I am trying to center align the text in a Label widget using the `with_text_alignment` method.
However, using `TextAlignment::Center` does not appear to change the text.

The system I am using is running Debian Sid with `libgtk-3-dev` version `3.24.30-3`.

Here is a quick sample program I put together to demonstrate my issue.

```
use druid::widget::{BackgroundBrush, Flex, Label};
use druid::{
    AppLauncher, Color, Data, Lens, LocalizedString, TextAlignment, Widget, WidgetExt,
    WindowDesc,
};

const WINDOW_TITLE: LocalizedString<State> = LocalizedString::new("Hello World");

#[derive(Clone, Data, Lens)]
struct State {
    text: String,
}

fn main() {
    // describe the main window
    let main_window = WindowDesc::new(build_root_widget)
        .title(WINDOW_TITLE)
        .window_size((400.0, 400.0));

    // create the initial app state
    let initial_state = State {
        text: "Hello World".into(),
    };

    // start the application
    AppLauncher::with_window(main_window)
        .launch(initial_state)
        .expect("Failed to launch application");
}

fn build_root_widget() -> impl Widget<State> {
    // create a label with centered text
    let label = Label::new("Hello World").with_text_alignment(TextAlignment::Center);

    // create the layout
    // give the label a fixed width and a red background
    let layout = Flex::row().with_child(label.fix_width(400.0).background(BackgroundBrush::Color(
        Color::from_hex_str("#FF0000").unwrap(),
    )));

    layout
}
```
The above code results in the following.

![text_align](https://user-images.githubusercontent.com/31593320/134606475-7ddd6af6-ef79-4146-9b4e-1d8a2bc69bf9.png)

Thank you for taking the time to look at my issue.

**Comment by cmyr** [comment]
The issue is that text alignment is about line positioning *within the layout rectangle*, and for a single-line label, the layout rectangle is simply the bounding rectangle of the text, not the label object itself. In general text alignment is mostly useful for multi-line text, where individual lines can be positioned variously depending on the total layout width.

If you just wish to have a centered label, you can do this by putting the label in an `Align` widget before setting its size, e.g. `label.center().fix_width(400)`.

In your sample app, the whole `Flex` is unnecessary.

**Comment by odakaui** [comment]
Ok. Thank you very much!
