### ISSUE TITLE
Any plan for a webview widget?

### ISSUE THREAD

**Issue by longrunsoul** [linebender/druid#2090]
Hello~

Thanks for such a great project. It is really amazing!

Just want to know that is there any possibility for a webview widget?
I need a webview widget to live render HTML content. I have looked into crate [web-view](https://github.com/Boscop/web-view) but don't know how to embed it in a window as a control.
Is there any way to do so?

Thanks.

**Comment by cmyr** [comment]
This is not planned for the foreseeable future, unfortunately, although it is certainly an important part of a GUI framework. Doing this in a cross-platform way is a pain. :(

**Comment by longrunsoul** [comment]
I see. Thank you very much!
Have a nice day~

**Comment by NickLarsenNZ** [comment]
@cmyr could there be a way to integrate https://github.com/tauri-apps/webkit2gtk-rs?

**Comment by cmyr** [comment]
I can't tell much from that link, unfortunately. In general though i would expect this to require a separate implementation on each target platform, that wraps whatever webview is available on that platform. The real problem is that we don't work with the system compositor, so there's not currently a way for us to embed content rendered elsewhere into our canvas.
