### ISSUE TITLE
[Question] How to highlight text? (and add links)

### ISSUE THREAD

**Issue by saona-raimundo** [linebender/druid#2285]
First of all, thanks a lot for the project!

I am looking into highlighting part of my text. I thought it would be an attribute of [RichText](https://docs.rs/druid/0.7.0/druid/text/struct.RichText.html), but I could not find it. Is there somewhere else I should look for?

I looked at the master branch in git and noticed that there is a `druid::text::RichTextBuilder` coming up, together with `druid::text::AttributesAdder`. I noticed that there is no "highlight" (or background) attribute here either.

Also, I noticed that, in the master branch, `druid::text::Link` can only be added through `druid::text::AttributesAdder` and not directly through `druid::text::RichText` nor `druid::text::RichTextBuilder`. 

## Question

Is there a reason for `RichText` not having an API to add backgrounds or links as attributes?

## Proposals

As for an API proposal, from the little I have seen, I could recommend enlarging `druid::text::Attribute` with two variants:
- `Background(KeyOrValue<Color>)`
- `Command(druid::Command)`

And adding the 
`background(&mut self, color: impl Into<KeyOrValue<Color>>) -> &mut Self` 
method to `druid::text::AttributesAdder`.

## Implementation

Adding the `Command` variant to `Attribute` seems very straight forward. I would not know how to add the background though.

**Comment by cmyr** [comment]
Links are a special case because they are more than just an attribute on the text, they also require things like cursor tracking and click handling, which requires closer integration with the widget.

As for why background color is not configurable, I don't have a great answer. There is also no API for explicit background color in piet; what there is instead is the api `rects_for_range`, which given a range of text returns the rectangles that correspond to the typographic bounds of that text (multiple rectangles because the text might be split across multiple lines) and these rects are specifically suitable for things like drawing selection regions.

To see how to use this API to actually draw rectangles, take a look through the textbox implementation to see how we draw the selection highlight.

**Comment by saona-raimundo** [comment]
Thank you so much! 

Just to be sure. For now, to have highlighted text "as part of RichText", I would have to write my own widget based on RichText and how TextBox draws a selection of text, right?

**Comment by xStrom** [comment]
I believe so, yes.
