### ISSUE TITLE
Scrollbar overlay vs inlay

### ISSUE THREAD

**Issue by ForLoveOfCats** [linebender/druid#608]
The current scrollbars of the Scroll widget are overlay meaning that they are painted over the child content and usually fade out when not being interacted with. An inlay scrollbar (for a lack of a better term) instead reserves space to draw itself outside the child content and optionally may or may not fade out.

Overlay scrollbars are generally more visually pleasant and allow the child to have a few more pixels to draw in. Conversely when hidden it is not immediately obvious that the content can be scrolled, the user has to fish for the scrollbar in order to interact with it via the mouse, and the user cannot click in an area of the scrollbar track to have the scrollbar slide/jump to that location.

Inlay scrollbars are more "useful" and accessible due to indicating when a Scroll can be scrolled, clicking in the track allowing sliding/jumping to the mouse, and in most cases not fading out the handle when not being interacted with. However they are less flashy than overlay scrollbars, take up slightly more space, and could cause additional complexity due to changing the size of the Scroll child when the track appears and disappears when it is needed/not needed.

My own preference is for inlay scrollbars, I'm implementing a text editor currently using druid and having the scrollbars be overlay is bothering me more than I expected it to. The choice between the two styles *could* be toggle-able but I don't know if it is worth supporting both with the additional complexity that would entail.

**Comment by cmyr** [comment]
yea, this is a tricky one. The whole gui world has definitely moved to floating scroll bars, but they are definitely worse from a pure usability standpoint. 

I _suspect_ that if we wanted to do this we might just want to make it be a separate widget. I'm not 100% sure though?

**Comment by xStrom** [comment]
### Overlay vs inlay
I prefer inlay for the same reason I dislike cookie banners. I want to see the actual content, not some auxiliary thing floating on top of it. I can also imagine a quite literal edge case where the scrollable content has buttons. You move to the mouse cursor from the outside to the button, but then BAM! a scrollbar appears on top of it and steals the click event.

### Fade vs always visible
I prefer always visible for usability reasons. Fading scrollbars definitely provide a cleaner look, but also make the UI harder to use. First, you have to know that a scrollbar can even appear. I've had plenty of over-the-shoulder experiences with friends who fail to use some fancy UI because the clickable elements only appear on hover. Secondly, even if you know a scrollbar will appear, it will now require two mouse movements instead of one. First to the scrollbar area to get the scrollbar to appear and then another movement to actually select the scrollbar, which only covers part of the scrollbar area.

### Opinionated vs complexity
The fade/visible choice can probably be just a simple boolean, so choice can be provided with almost no complexity increase.

For the overlay/inlay difference I'm not sure how much the implementations would diverge and increase the maintenance burden. Probably easiest to just implement it and see how it goes.

**Comment by s3thi** [comment]
I prefer overlay scrollbars, but I see the usefulness of always-visible inlay scrollbars too. I feel this should be a configurable flag.

On macOS, the default is overlay scrollbars if you're using a trackpad or the Apple Magic Mouse. If you plug in a third-party USB mouse, the enitre OS switches to inlay scrollbars instead. This was true at least a few months ago when I was using a mouse with my computer, thing might have changed now. Regardless, this is a useful feature that Druid might want to emulate. It's easier to operate inlay scrollbars with a mouse, and overlay scrollbars with a good trackpad.

**Comment by ForLoveOfCats** [comment]
I was worried about the cognitive cost of supporting both but I think I'll take a jab at it over the weekend.

However I don't think that a flag to disable fade out for overlay would be very desirable. At that point the scrollbar is permanently obscuring some part of the content. I dunno :man_shrugging:
