### ISSUE TITLE
macOS: Support choosing file formats in the file dialog.

### ISSUE THREAD

**Issue by xStrom** [linebender/druid#998]
When a user is saving a file they should be able to choose from among the supported file formats.
The Windows and GTK implementations already support this and other apps on macOS support this.

![file-formats](https://user-images.githubusercontent.com/754881/83332941-b8632e80-a2a6-11ea-9fdf-87f986c54b1d.png)

According to Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/file-handling/) this should be possible even without a custom extension.

> **Let the user choose an output format if your app can save in multiple file formats.** Output formats, when present, are displayed via a pop-up button beneath the output location.

It's unclear how these *output formats* can be specified. [`NSSavePanel`](https://developer.apple.com/documentation/appkit/nssavepanel) only seems to have [`allowedFileTypes`](https://developer.apple.com/documentation/appkit/nssavepanel/1534419-allowedfiletypes) which we are using already. However the way we are using them is just an array of strings, so we couldn't even specify the format name like *Rich Text Document*.

The `allowedFileTypes` also seems to support [UTIs](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_intro/understand_utis_intro.html). Would we get the format selection if we defined UTIs? Are there other ways to get the format selection?

**Comment by malleusinferni** [comment]
Some light research suggests that the popup menu must be created manually, supplied to the save panel as an [`accessoryView`](https://developer.apple.com/documentation/appkit/nssavepanel/1525544-accessoryview), and equipped with callbacks that modify `allowedFileTypes` with the selected extension. I tried creating a simple counterexample from system-defined UTIs, but the format selection menu did not appear.

**Comment by xStrom** [comment]
It's definitely possible via an accessory view, but the reason I'm thinking it might be possible in another way is the wording of the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/file-handling/). At the end of that page the accessory view extending and the format pop-up are described separately.

Of course this might also be a another Catalina thing, where previously the pop-up showed up without an accessory view but that's no longer the case in Catalina. Would need someone with an older macOS to comment on that.

**Comment by terhechte** [comment]
I started working on this and have a implementation that fulfills the requirement:

<img width="440" alt="Screen Shot 2021-07-02 at 11 41 21" src="https://user-images.githubusercontent.com/132234/124255532-8f0c7600-db2a-11eb-9a68-3afac06f5dfc.png">

There is a way to get this behaviour for free, but only if the application uses `NSDocument`. Otherwise, one has to build this using custom UI (e.g. a `NSView`, a `NSTextField`, and a `NSPopupButton`).

While I have the UI working, I have trouble returning the proper result. On macOS, such a dialog results in two pieces of data: 
- The selected file path
- The selected file format

However, the `FileInfo` struct only has one piece of data:

``` rs
/// Information about the path to be opened or saved.
///
/// This path might point to a file or a directory.
#[derive(Debug, Clone)]
pub struct FileInfo {
    pub(crate) path: PathBuf,
}
```

So how do I coalesce these two data into one. My initial approach was to take the path and replace the extension with the chosen extension from the file format. However, this omits crucial data. There might be situations where the file ending is the same, but the file data is different depending on the output format. E.g. I'm generating HTML and the output formats are "HTML with Javascript" and "HTML without Javascript". Or Blender files they're always `.blend` but can be `blender 2, blender 2.4, blender 2.6, etc`. Now, I can't think of a great example of similar file extensions with different data, but you get the gist.

So the other option would be to expand FileInfo:
``` rs
pub struct FileInfo {
    pub(crate) path: PathBuf,
    pub(crate) format: FileSpec
}
```

But this would be breaking and surely affect the other platforms. I didn't look into it yet but I'd just imagine that the file choosers on other platforms don't let you access the chosen format after the fact. So I'd just go with the rewritten output `path` instead of opting for the additional `format` complexity, but I still wanted to raise the point.

I'll post a link to the interim branch once I'm done cleaning it up.

**Comment by cmyr** [comment]
I'm okay with modifying `FileInfo` to include additional information, even if this isn't used consistently on all platforms. I would maybe consider making the field, `Option<FileSpec>`, or similar? It would be an opportunity for the platform to provide additional information about how the file should be saved, and I think this is totally reasonable.

**Comment by terhechte** [comment]
I've updated the branch accordingly and tried to add documentation.
